### ISSUE TITLE
load ventus with require

### ISSUE THREAD

**Issue by erickChavez** [rlamana/Ventus#15]
Hi, how do i load ventus with requirejs. I tried to load like this without any success: 
ventus: '../assets/libs/Ventus/build/ventus.min'

**Comment by macqm** [comment]
@erickChavez: Did you use shim config? I use it in (although in Browserify) and works for me.

**Comment by rlamana** [comment]
Well, you shouldn't have to use a shim config since the library supports amd. This line is supposed to do the trick: https://github.com/rlamana/Ventus/blob/master/dist/ventus.js#L7

**Comment by JWGmeligMeyling** [comment]
It imports jquery as '$'. Thefefore you should map 'jquery' to '$':

```js
requirejs.config({
    baseUrl: 'bower_components',
    paths: {
        'jquery' : 'jquery/dist/jquery.min',
        'ventus': 'Ventus-Bower/dist/ventus'
    },
    map: {
        '*': {
            '$' : 'jquery'
        }
    }
    }
});
```

**Comment by rlamana** [comment]
Thanks for your comment @JWGmeligMeyling, it is now imported as the more standard 'jQuery' (https://github.com/rlamana/Ventus/commit/d3fffede8a13e9fe6c62eacebb3031f6f577671d)

I'd love to remove the jQuery dependency in the future though.

**Comment by JWGmeligMeyling** [comment]
Well for me jQuery is not really a show stopper. I love Ventus as it is :smile: Thanks for the good work!

**Comment by amatiasq** [comment]
Less dependencies more reasons to love it :+1:
