### ISSUE TITLE
Usage questions.

### ISSUE THREAD

**Issue by nologic** [rlamana/Ventus#16]
Hello,

Thank you for creating Ventus! I'm trying to use it but struggling with some configurations options. Please advice me on the following:

 - How can bind window managing to a particular div? I don't want it to take over the entire document.
 - How can I turn off the window shaking when selected by the mouse? While it looks quite cool, I don't want it there all the time.
 - How can I enable horizontal scrolling within the windows? Vertical is already there, but not quite sure when it's not doing the horizontal.

Thanks in advance,
Mike.

**Comment by rlamana** [comment]
Sorry for my late response,
 1. Right now this option is not supported. The window manager gets added under ```document.body``` in the DOM tree. This happens in line 19: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/windowmanager.js#L19

 2. Overwrite the ```animation``` property of css class ```.wm-window.move```.

 3. Use css ```overflow: scroll``` in the main container of your wrapped HTML code. Windows are simple wrappers of your code, this is up to the developer using the library. At some point we can add code to handle better, or make it better for developers to define that.
