### ISSUE TITLE
Ignore dist/ folder and move to CDN hosting

### ISSUE THREAD

**Issue by macqm** [rlamana/Ventus#23]
I just had a thought that it isn't perhaps the best idea to keep builds in dist folder. Sooner or later it will lead to conflicts with merge. Maybe instead the folder should be ignored and the latest build could be hosted over a content delivery network? This seems to be a good place to look at: [jsDelivr](https://github.com/jsdelivr/jsdelivr).

**Comment by rlamana** [comment]
I totally agree, until now I was the only contributor so I didn't care much about it, but now it makes perfect sense. I'll take a look at jsDelivr.

Now that you added tests I'll probably use travis to integrate a CI to the project.

**Comment by rlamana** [comment]
Done. I just ignored ```dist/```and added Travis integration.

**Comment by rlamana** [comment]
@macqm Instead of using jsDelivr, I added ventus as a bower component. Check it:
```bower install ventus``` should work now.

Ventus compiled files are included in the new [Ventus-Bower](https://github.com/rlamana/Ventus-Bower) repository just created.

**Comment by macqm** [comment]
Fantastic! Thanks a lot :)
