### ISSUE TITLE
Elements design - Own theme for windows

### ISSUE THREAD

**Issue by DaniellMesquita** [rlamana/Ventus#28]
Windows will have the Ventus' theme and his usable elements.

**Comment by rlamana** [comment]
Window manager is themable via CSS. Do you mean to make a more standard/options way to package themes? what do you exactly mean here?

**Comment by DaniellMesquita** [comment]
"make a more standard/options way to package themes", yes. Use default UI for scrollbars, buttons, radius, etc.

**Comment by DaniellMesquita** [comment]
The customization for buttons, radios, scrollbars, etc. is for environment side. Sorry :+1:
