### ISSUE TITLE
Window menus

### ISSUE THREAD

**Issue by DaniellMesquita** [rlamana/Ventus#29]
The windows will have a dropdown menu for user select options.

**Comment by rlamana** [comment]
What options would those be?

**Comment by DaniellMesquita** [comment]
Are not important the options for system, only for demos. The important part is the system and design of menus.

**Comment by DaniellMesquita** [comment]
I've readed some comments now. Really, don't have need for an window menu that can be default of environment/OS or the propen app. Thanks :smile:
