### ISSUE TITLE
Frameless windows

### ISSUE THREAD

**Issue by DaniellMesquito** [rlamana/Ventus#31]
Give example and option to user create frameless windows.
31/07/2016 **Edit**: I've removed the part "with possibility to activate option to click throught transparency" due to the separated issue #56.

**Comment by rlamana** [comment]
Good to have

**Comment by DaniellMesquita** [comment]
@rlamana Is possible program in javascript for when activated "click throught transparency" ever transparent part of image can have "pointer-events:none" property?

**Comment by DaniellMesquita** [comment]
@rlamana will be an amazing idea supporting the same API of NW.js for frameless windows.
https://github.com/nwjs/nw.js/wiki/Frameless-window
http://stackoverflow.com/questions/3680429/click-through-a-div-to-underlying-elements

**Comment by DaniellMesquito** [comment]
@rlamana, please assign me to it.

**Comment by DaniellMesquito** [comment]
Suggested the "click throught transparency" feature in #56.

**Comment by DaniellMesquito** [comment]
> @rlamana  commented on 24 Jan
Good to have

> DaniellMesquito commented 3 days ago
> @rlamana, please assign me to it.

`@rlamana closed this 17 hours ago`

---------------------------------------------------

> @rlamana  commented on 24 Jan
Good to have
