### ISSUE TITLE
Unfocus window on click out

### ISSUE THREAD

**Issue by DaniellMesquito** [rlamana/Ventus#36]
Unfocus window when click out the window, not only when click in other windows.

**Comment by rlamana** [comment]
This

**Comment by DaniellMesquito** [comment]
@rlamana, please assign me to it.

**Comment by DaniellMesquito** [comment]
> @rlamana closed this [on 24 Jan](https://github.com/rlamana/Ventus/issues/36#event-524431831)
> ----------------------------------------------------------------------------------------------------------------@rlamana reopened this on [24 Jan](https://github.com/rlamana/Ventus/issues/36#event-524431839)
> ----------------------------------------------------------------------------------------------------------------
> rlamana added the [enhancement](https://github.com/rlamana/Ventus/labels/enhancement) label [on 24 Jan](https://github.com/rlamana/Ventus/issues/36#event-524432059)
> ----------------------------------------------------------------------------------------------------------------
> @DaniellMesquito commented [3 days ago](https://github.com/rlamana/Ventus/issues/36#issuecomment-236407791)
> 
> > @rlamana, please assign me to it.
> 
> ----------------------------------------------------------------------------------------------------------------
> @rlamana closed this [17 hours ago](https://github.com/rlamana/Ventus/issues/36#event-742741577)

@rlamana & Ventus'/Daniell's new freemason followers @amatiasq and @RyanRiffle, this is a joke?

Congratulations for @macqm and @blueqnx that joined Ventus when this was a serious project.
