### ISSUE TITLE
Script for independent apps

### ISSUE THREAD

**Issue by DaniellMesquita** [rlamana/Ventus#41]
People will can run own apps in web with the power of this WM, like sandwich menu, window menu and context menu.

**Comment by DaniellMesquita** [comment]
Too, this will be usefull to independent Terminus and Todo apps.

**Comment by rlamana** [comment]
The ideo of the window manager is to be independent from the "App" or the script that the window wraps. This is out of the scope of the library in my opinion. It would be more OS / environment related.
