### ISSUE TITLE
"Open new window" button in Exposé Mode

### ISSUE THREAD

**Issue by DaniellMesquito** [rlamana/Ventus#48]

**Comment by amatiasq** [comment]
Do you think this is really useful? I mean as I understand it Exposé mode was created to choose between opened windows, I don't see the point on creating new windows in Exposé mode :\

**Comment by DaniellMesquita** [comment]
Exposé is an type of task manager, then is really useful the possibility to open new window/app directly from the same place that user close apps.
Exposé is not only to terminate apps, but too to open apps. Is an task manager ;)

**Comment by DaniellMesquito** [comment]
@rlamana, please assign me to it.
