### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [rlamana/Ventus#57]
Hello @rlamana ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the dependency file need to be grab on [github](https://github.com/rlamana/Ventus).
I think the main file I need to add is `src/ventus.js`.
Are there any other dependency needed?
Like `src/ventus/wm/window.js` and ` src/ventus/wm/windowmanager.js`.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8684
https://github.com/cdnjs/cdnjs/pull/8973

**Comment by kennynaoh** [comment]
Hello @rlamana ,
And there is another question about `ventus.js` want to ask.
I found that another code on your [website](http://www.rlamana.es/ventus/code/dist/ventus.js) is different from [github](https://github.com/rlamana/Ventus/blob/master/src/ventus.js) you publish.
Please help me confirm that.
Thanks!

**Comment by rlamana** [comment]
Hi @kennynaoh,
Actually the needed compiled files were not part of the repository. I just added them, so you can grab them here for tagged version 0.2.1: 
https://github.com/rlamana/Ventus/blob/v0.2.1/dist/ventus.js 
or the minimized version:
https://github.com/rlamana/Ventus/blob/v0.2.1/dist/ventus.min.js
Thank you!

**Comment by rlamana** [comment]
As for the website version, it might be outdated. I will update it to the latest version ASAP.

**Comment by kennynaoh** [comment]
Thanks @rlamana ,
What about the old version `v0.2`?
Please help me confirm this.
Thanks!
