### ISSUE TITLE
Doesn't work under Electron (node.js)

### ISSUE THREAD

**Issue by kurisubrooks** [rlamana/Ventus#58]
Unfortunately it seems I can't get Ventus to run under Electron. 
Electron is a desktop Chromium wrapper with node.js integration.

Tested using the examples provided in the download

![image](https://cloud.githubusercontent.com/assets/6291467/20048694/92aab98c-a512-11e6-87f2-553362653e5b.png)

```
Uncaught Error: ventus/wm/window missing ventus/core/emittermain
Uncaught ReferenceError: Ventus is not defined
```

**Comment by rlamana** [comment]
It looks like you are missing some dependencies. Are you sure you are importing this file: https://github.com/rlamana/Ventus/blob/master/dist/ventus.min.js ?

**Comment by kurisubrooks** [comment]
Yes, that's the file i'm using. 
I've tried with both `<script src>` and node's `require`, but i'm unable to get it to work at all.

**Comment by amatiasq** [comment]
Maybe the dependency is there but this Electron environment is breaking the way Ventus load modules.

**Comment by kurisubrooks** [comment]
That's what i'm thinking. Most JS libs i've used so far tend to have to include node.js compatible builds of their libs, so i'm guessing it might be a problem on your end. 

If you'd like to reproduce;

Install Electron (via npm) `[sudo] npm i -g electron-prebuilt`, run `electron`, then drag in `index.html` (from `dist`) to the "Drop app here" section of the window

**Comment by rlamana** [comment]
The way I export the module is kind of old fashioned, I agree that the issue is probably there. I will take a look as soon as possible. Thanks for the feedback.

**Comment by kurisubrooks** [comment]
Just as a suggestion; you might want to look into UMD. 
It seems to be what most people use when exporting modules for javascript nowadays, and is compatible with browser and node.js

Article;
https://garrettn.github.io/blog/2014/02/19/write-modular-javascript-that-works-anywhere-with-umd/

**Comment by rlamana** [comment]
The problem was actually a few files that were not using require.js and since Electron has a node.js runtime these files were automatically using 'module.exports' instead.

It works now. However, at some point I should improve the dependency management.

**Comment by kurisubrooks** [comment]
Sorry, now i'm getting a different problem. 
Stylesheet is properly defined in the document `<link href="../system/design/ventus.css" rel="stylesheet">`

![image](https://cloud.githubusercontent.com/assets/6291467/20085229/7b2d4e7e-a5bb-11e6-816d-29d9f90fc37f.png)

Sorry for so much hassle 😭

**Comment by rlamana** [comment]
This version of the library needs jQuery (a dependency I will completeley remove when I have the time). Are you sure you loaded it? has your jQuery version 'cssHooks'?  https://api.jquery.com/jQuery.cssHooks/

**Comment by kurisubrooks** [comment]
I'm using the node.js release of jQuery, but yes it's available.

![image](https://cloud.githubusercontent.com/assets/6291467/20092766/d06eef6e-a5ed-11e6-88bd-bee6a70c074a.png)

It seems `$.cssHooks` is also available.

![image](https://cloud.githubusercontent.com/assets/6291467/20092820/22f66f82-a5ee-11e6-9f3e-c7f24950f408.png)

**Comment by rlamana** [comment]
I'll try to reproduce it but is there any place where I can take a look at your code?

**Comment by kurisubrooks** [comment]
Sure, it's a private repo. Let me give you access.
