### ISSUE TITLE
Way to disable Exposé

### ISSUE THREAD

**Issue by kurisubrooks** [rlamana/Ventus#62]
Is there one? I went through the code and couldn't find any way to config or anything, so, would I have to just modify the code and remove it alltogether?

**Comment by rlamana** [comment]
I'm afraid there is not easy way to do this right now. This should be implemented by creating an 'unregister' method in the expose plugin to remove this listener: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/modes/expose.js#L16

As a quick solution you might want to try to do this to your window manager object:
`windowmanager.el.disconnect('contextmenu');`

**Comment by kurisubrooks** [comment]
Unfortunately i'm guessing `wm.el.disconnect is not a function(…)`. Logging the class seems to back that up.
![image](https://cloud.githubusercontent.com/assets/6291467/22585501/3b4e0b10-ea4c-11e6-814a-aa6ccae7eab3.png)

**Comment by Skyne98** [comment]
any progress here?

**Comment by kurisubrooks** [comment]
Unfortunately, still waiting for a response.

**Comment by rlamana** [comment]
Another easy way to do this would be to remove 'expose' of the list of posible modes.

`yourWindowManager.modes.expose = undefined`

Let me know if that solves your issue.
