### ISSUE TITLE
WindowManager.prototype is polluted by multiple instances.

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [rlamana/Ventus#66]
I'm creating this issue with the intention of submitting a PR for it soon.

When multiple instances of `WindowManager` are created, its `prototype` is polluted by these two lines in the constructor:
```
		// Binding sub-functions to this object
		this.createWindow.fromQuery = this.createWindow.fromQuery.bind(this);
		this.createWindow.fromElement = this.createWindow.fromElement.bind(this);
```
The `createWindow` method is of course assigned from the prototype to every instance, so setting properties on this method will of course set those properties for every instance as well. This means that after the first time the constructor is run, the two properties are set to bound functions. Creating a second instance will only attempt to bind already bound functions, resulting in the wrong context being used for subsequent instances of `WindowManager`.

Arguably, this library was not written with the intention of supporting multiple instances of `WindowManager` (given the way it modifies the DOM on the top-level and such); however, the pollution of the prototype is of a great enough concern that I believe this issue still warrants fixing.

**Comment by amatiasq** [comment]
Good catch!
