### ISSUE TITLE
Windows snap like functionality

### ISSUE THREAD

**Issue by laggingreflex** [rlamana/Ventus#68]
Awesome library! 

Windows has a neat snap functionality: https://www.youtube.com/watch?v=Bk8yTBLEj3c

Would it be possible to add this type of functionality?

**Comment by rlamana** [comment]
Thanks!
That's a cool feature and could definitely be added. However, the purpose of the library at the time it was created was to serve as an experiment and it was never meant to be maintained. If you wish to work on such a cool feature, feel free to contribute and send me a PR.
