### ISSUE TITLE
not really an issue more of a "how do i"

### ISSUE THREAD

**Issue by develperbayman** [rlamana/Ventus#87]
hello i was just wondering how would one open a closed window from an html file trying to use a button?
i closed all the windows in the desktop example now im trying to open them on command so i can create a taskbar

also i closed them in the desktop.js file like so:
here is the code:

		// Open windows
			//	openWithDelay(terminalWin, 0);
			//	openWithDelay(todoWin, 200);
			//	openWithDelay(aboutWin, 400);
			//	openWithDelay(playerWin, 600);
			});

to open the terminal with a button in html
here is my code:

` <li>
     <span>Terminal</span>
        <a id="myLink" onclick="opentab (terminalwin();><img src="images/terminal.png"/></a>
     </li>`

iv also tried this but no dice
my other code:
` <li>
     <span>Terminal</span>
        <a href="#" onclick=terminal-app.onclick = openWithDelay(terminalWin, 0);><img src="images/terminal.png"/></a>
     </li>`

and iv tried this:
`<li>
     <span>Terminal</span>
        <a href="#" onclick=var terminalWin = wm.createWindow.fromQuery('.terminal-app', {
			title: 'Terminal',
			classname: 'terminal-window',
			width: 600,
			height: 300,
			x: 50,
			y: 60
		});

		terminalWin.signals.on('click', function(win){
			terminal.display.focus();
			openWithDelay(terminalWin, 0);
			><img src="images/terminal.png"/></a>
     </li>`

what am i doing wrong here?? how would anyone eles do 

thanks

**Comment by develperbayman** [comment]
and i tried it like this
` <li>
     <span>Terminal</span>
        <a href="#"onclick="document.getElementById('terminal-app').innerHTML = openWithDelay(terminalWin, 0);">
><img src="images/terminal.png"/></a>`

but still to no avail......i hate getting hung up on one simple line of code

**Comment by rlamana** [comment]
Try not to mix content and behavior when using raw js/html approach like this. Give your `<a>` and ID and from javascript attach to the element an event handler. For example:

```html
<a id="mybutton" href="#"></a>
```

And in your javascript:

```js
document.querySelector("#mybutton").addEventListener('click', function() {
   terminalWin.open();
});
```
`openWithDelay` is just a function I created for the example to open window with a cooler effect, use directly the open method in the window object.

Hope that helps.

**Comment by develperbayman** [comment]
actually thank you so much im trying to get the sysmantics of javascript
down i have always not been the best programmer and im still learning
github i know its hard to belive iv been in i.t for over 25 yrs

opened my first faqcebook account just a few yeas ago im so behind in
everything

if i add-on to ventus would you want me to upload it to github or just
email it to you so you can???

thanks a bunch again for the clear example
,jeremy
